apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: thoughtdata-letsencrypt
        emptyDir: {}
      nodeSelector:
        app: 'true'
      containers:
      - name: nginx
        image: eu.gcr.io/peopledata-product-team/td.nginx:{{ENV.GO_PIPELINE_COUNTER}}
        imagePullPolicy: Always
        env:
        - name: LETSENCRYPT
          valueFrom:
            configMapKeyRef:
              name: namespace-config 
              key: letsencrypt.enabled 
        - name: LETSENCRYPT_EMAIL
          value: 'peopledata-product-team@thoughtworks.com'
        - name: HOST_GATEWAY
          valueFrom:
            configMapKeyRef:
              name: namespace-config 
              key: host.gateway
        - name: HOST_DASHBOARD
          valueFrom:
            configMapKeyRef:
              name: namespace-config
              key: host.dashboard
        - name: HOST_RABBITMQ
          valueFrom:
            configMapKeyRef:
              name: namespace-config 
              key: host.rabbitmq
        volumeMounts:
          - name: thoughtdata-letsencrypt
            mountPath: /etc/letsencrypt/live
        ports:
        - containerPort: 80
        - containerPort: 443
